export enum ActionType {
  updateCheckItemStateOnCard = "updateCheckItemStateOnCard",
  addMemberToCard = "addMemberToCard",
  createCard = "createCard",
  updateCard = "updateCard",
  addAttachmentToCard = "addAttachmentToCard",
  deleteCard = "deleteCard",
  addChecklistToCard = "addChecklistToCard",
  commentCard = "commentCard",
  updateList = "updateList",
  createList = "createList",
  moveCardToBoard = "moveCardToBoard",
  updateBoard = "updateBoard",
  updateChecklist = "updateChecklist",
  removeChecklistFromCard = "removeChecklistFromCard",
  addMemberToBoard = "addMemberToBoard",
  enablePlugin = "enablePlugin",
  disablePlugin = "disablePlugin",
  addToOrganizationBoard = "addToOrganizationBoard",
  createBoard = "createBoard",
}
