kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: node:latest
  commands:
  - yarn
  
- name: test
  image: node:latest
  commands:
  - yarn test
  
trigger:
  event:
    include:
    - push
    - pull_request
