kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: node:latest
  commands:
  - yarn
  
- name: test
  image: node:latest
  commands:
  - yarn test
    
trigger:
  branch: 
  - master
  event:
  - pull_request
  - push

